# Generated by Django 4.0.1 on 2022-03-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_verificationrequest_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='status',
            field=models.CharField(choices=[('RQ', 'Requested'), ('VR', 'Verified by requester'), ('VG', 'Verified by given')], default='RQ', max_length=2),
        ),
    ]
