# Generated by Django 4.0.1 on 2022-02-14 11:42

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=phone_field.models.PhoneField(default='00000000000', help_text='Contact phone number', max_length=31),
            preserve_default=False,
        ),
    ]
